#!/bin/sh

exec < /dev/tty

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.(php|twig) `
BIN_DIR=`composer config bin-dir 2>&1 | tail -1`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

SERVICE_PHP_NAME=$(grep SERVICE_PHP_NAME .env | xargs)
SERVICE_PHP_NAME=${SERVICE_PHP_NAME#*=}
if [ "$SERVICE_PHP_NAME" = "" ]; then
    SERVICE_PHP_NAME="app"
fi

if [ `docker ps -q --no-trunc | grep $(docker-compose ps -q $SERVICE_PHP_NAME)` ]; then

    echo "Checking PHP Lint..."
    for FILE in $SFILES
    do
        docker-compose exec -T $SERVICE_PHP_NAME php -l -d display_errors=0 $FILE
        if [ $? != 0 ]
        then
            echo "Fix the error before commit."
            exit 1
        fi
    #    FILES="$FILES $PROJECT/$FILE"
    done


    if [ "$SFILES" != "" ] && [ -f "$BIN_DIR/phpcs" ]
    then
        echo "Running Code Sniffer. Code standard PSR2."
        docker-compose exec -T $SERVICE_PHP_NAME $BIN_DIR/phpcs --standard=PSR2 --colors --encoding=utf-8 -n -p $SFILES
        if [ $? != 0 ]
        then
            echo "Fix the error before commit!"
            echo "Run"
            echo "docker-compose exec -T $SERVICE_PHP_NAME $BIN_DIR/phpcs --standard=PSR2 --colors --encoding=utf-8 -n -p $SFILES"
            echo "for automatic fix or fix it manually."
            exit 1
        fi
    fi

    if [ "$SFILES" != "" ] && [ -f "$BIN_DIR/phpstan" ]
    then
        echo "Running PHPStan."
        docker-compose exec -T $SERVICE_PHP_NAME $BIN_DIR/phpstan analyse --configuration=phpstan.neon.dist --error-format=raw --autoload-file=vendor/autoload.php $SFILES
        if [ $? != 0 ]
        then
            echo "Fix the error before commit!"
            echo "Run"
            echo "docker-compose exec -T $SERVICE_PHP_NAME $BIN_DIR/phpstan analyse --configuration=phpstan.neon.dist --error-format=raw --autoload-file=vendor/autoload.php $SFILES"
            echo "for automatic fix or fix it manually."
            exit 1
        fi
    fi

else

    read -p "No docker up; commit without test php? [y/n](n):" proceed

    if [ "$proceed" != "y" ]; then
        echo "Commit stopped"
        exit 1
    fi

fi

exit $?